import type { FormConfig } from "./types";

export const contactForm = {
  legend: "Formulario de contacto",
  submitLabel: "Enviar mensaje",
  accessKey: import.meta.env.PUBLIC_WEB3FORMS_CONTACT_KEY,
  subject: "Vida en Turra · Nuevo mensaje de contacto",
  note: "Todos los campos son obligatorios.",
  successMessage: "Tu mensaje se ha enviado. Gracias por contactar con la asociación.",
  fields: [
    {
      name: "name",
      type: "text",
      label: "Nombre",
      autocomplete: "name",
      placeholder: "Tu nombre",
      maxLength: 120,
      required: true,
      requiredMessage: "Escribe tu nombre.",
    },
    {
      name: "email",
      type: "email",
      label: "Correo electrónico",
      autocomplete: "email",
      placeholder: "tu@correo.es",
      maxLength: 254,
      required: true,
      requiredMessage: "Escribe tu correo electrónico.",
    },
    {
      name: "message",
      type: "textarea",
      label: "Mensaje",
      placeholder: "Cuéntanos tu idea…",
      maxLength: 5000,
      required: true,
      requiredMessage: "Escribe un mensaje.",
      fullWidth: true,
    },
    {
      name: "privacy",
      type: "checkbox",
      label: "He leído y acepto la política de privacidad.",
      required: true,
      requiredMessage: "Debes aceptar la política de privacidad.",
      fullWidth: true,
    },
  ],
} satisfies FormConfig;
