import type { FormConfig } from "./types";

export const membershipForm = {
  legend: "Solicitud de alta de socio",
  submitLabel: "Solicitar inscripción",
  accessKey: import.meta.env.PUBLIC_WEB3FORMS_MEMBERSHIP_KEY,
  subject: "Vida en Turra · Nueva solicitud de socio",
  note: "Nombre, apellidos, tipo y número de documento, correo, contribución anual y aceptación de privacidad son obligatorios. La asociación revisará tu solicitud.",
  successMessage: "Tu solicitud se ha enviado. La asociación se pondrá en contacto contigo para gestionar el alta.",
  fields: [
    {
      name: "name",
      type: "text",
      label: "Nombre",
      autocomplete: "given-name",
      placeholder: "Tu nombre",
      maxLength: 120,
      required: true,
      requiredMessage: "Escribe tu nombre.",
    },
    {
      name: "surname",
      type: "text",
      label: "Apellidos",
      autocomplete: "family-name",
      placeholder: "Tus apellidos",
      maxLength: 160,
      required: true,
      requiredMessage: "Escribe tus apellidos.",
    },
    {
      name: "documentType",
      type: "select",
      label: "Tipo de documento",
      required: true,
      requiredMessage: "Selecciona un tipo de documento.",
      options: [
        { value: "dni", label: "DNI" },
        { value: "nie", label: "NIE" },
        { value: "passport", label: "Pasaporte" },
      ],
    },
    {
      name: "documentNumber",
      type: "text",
      label: "Número de documento",
      placeholder: "Número del documento elegido",
      maxLength: 20,
      required: true,
      requiredMessage: "Escribe tu número de documento.",
      validation: "document",
      validationField: "documentType",
    },
    {
      name: "email",
      type: "email",
      label: "Correo electrónico",
      autocomplete: "email",
      placeholder: "tu@correo.es",
      maxLength: 254,
      required: true,
      requiredMessage: "Escribe tu correo electrónico.",
    },
    {
      name: "phone",
      type: "tel",
      label: "Teléfono",
      autocomplete: "tel",
      placeholder: "Tu teléfono",
      maxLength: 30,
    },
    {
      name: "contribution",
      type: "select",
      label: "Contribución anual",
      placeholder: "Selecciona cuánto quieres contribuir al año",
      required: true,
      requiredMessage: "Selecciona tu contribución anual.",
      fullWidth: true,
      options: [
        { value: "10", label: "10 €" },
        { value: "15", label: "15 €" },
        { value: "20", label: "20 €" },
        { value: "25", label: "25 €" },
        { value: "30", label: "30 €" },
      ],
    },
    {
      name: "privacy",
      type: "checkbox",
      label: "He leído y acepto la política de privacidad.",
      required: true,
      requiredMessage: "Debes aceptar la política de privacidad.",
      fullWidth: true,
    },
  ],
} satisfies FormConfig;
